### Get ranking
GET http://localhost:1234/ranking?limit=10&offset=10
 
### Get specific player
GET http://localhost:1234/player?id=52j3mubv8ktbdegc396l5w4f22

### Post a new player
POST http://localhost:1234/register
Content-Type: application/json

  {
    "id": "52j3mubv8ktbdegc396l5w4f",
    "score": 800
  }

### Update new maxScore
PUT http://localhost:1234/player/update-score
Content-Type: application/json

{
  "id": "22",
  "score": 12
}

# DEPLOYED API

### Post a new player
POST https://solanastackgameapi-production.up.railway.app/register
Content-Type: application/json

{
  "id": 2,
  "score": 250,
},